sudo: required
services:
    - docker

before-install:
    - docker build -t marekmikusek/docker-react -f Dockerfile.dev .

script: 
    - docker run -e CI=true marekmikusek/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "eu-west-3"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-3-624944001153"
    bucket-path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY