sudo: required
services:
    - docker

before-install:
    - docker build -t marekmikusek/docker-react -f Dockerfile.dev .

script: 
    - docker run -e CI=true marekmikusek/docker-react npm run test
